# Generated by Django 3.2.9 on 2021-12-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('sex', models.CharField(choices=[('ML', 'Male'), ('FL', 'Female')], max_length=2)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.ImageField(unique=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
