# Generated by Django 3.2.9 on 2021-12-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Yamdb User', 'verbose_name_plural': 'Yamdb Users'},
        ),
    ]
