# Generated by Django 3.2.9 on 2021-12-02 23:31

from django.db import migrations

import clients.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', clients.models.UserManager()),
            ],
        ),
    ]
