# Generated by Django 3.2.9 on 2021-12-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20211206_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.FloatField(default=59.7914),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lon',
            field=models.FloatField(default=30.165),
        ),
    ]
